### ISSUE TITLE
golang1.17.2 "fatal error: unreachable method called. linker bug?"

### ISSUE THREAD

**Issue by pkujhd** [pkujhd/godynamic#1]
```
[jhd@test-centos7-build-2-45 plugin]$ ./loader -l /home/jhd/go/pkg/linux_amd64_dynlink/libgithub.com-pkujhd-godynamic-examples-ubase.so -p github.com/pkujhd/godynamic/examples/ubase.so -r github.com/pkujhd/godynamic/examples/ubase.Enter 
fatal error: unreachable method called. linker bug?

goroutine 1 [running]:
runtime.throw({0x7fb946feb715, 0xc000012b30})
        /home/jhd/programs/go/src/runtime/panic.go:1198 +0x71 fp=0xc000373ab0 sp=0xc000373a80 pc=0x7fb9468bd671
runtime.unreachableMethod()
        /home/jhd/programs/go/src/runtime/iface.go:561 +0x25 fp=0xc000373ad0 sp=0xc000373ab0 pc=0x7fb9468882c5
fmt.(*pp).handleMethods(0xc0003a20d0, 0x0)
        /home/jhd/programs/go/src/fmt/print.go:620 +0x24c fp=0xc000373d80 sp=0xc000373ad0 pc=0x7fb9469d3c2c
fmt.(*pp).printArg(0xc0003a20d0, {0x7fb9475bed40, 0xc000012b30}, 0x76)
        /home/jhd/programs/go/src/fmt/print.go:709 +0x6b3 fp=0xc000373e20 sp=0xc000373d80 pc=0x7fb9469d4953
fmt.(*pp).doPrintln(0xc0003a20d0, {0xc000373f50, 0x1, 0x406b65})
        /home/jhd/programs/go/src/fmt/print.go:1169 +0x14f fp=0xc000373e90 sp=0xc000373e20 pc=0x7fb9469d83ef
fmt.Fprintln({0x60d7a0, 0xc000010200}, {0xc000373f50, 0x1, 0x1})
        /home/jhd/programs/go/src/fmt/print.go:264 +0x4f fp=0xc000373ee0 sp=0xc000373e90 pc=0x7fb9469d164f
fmt.Println(...)
        /home/jhd/programs/go/src/fmt/print.go:274
main.main()
        /home/jhd/go/src/github.com/pkujhd/godynamic/examples/loader/loader.go:25 +0x248 fp=0xc000373f80 sp=0xc000373ee0 pc=0x409808
runtime.main()
        /home/jhd/programs/go/src/runtime/proc.go:255 +0x282 fp=0xc000373fe0 sp=0xc000373f80 pc=0x7fb9468c0d22
runtime.goexit()
        /home/jhd/programs/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000373fe8 sp=0xc000373fe0 pc=0x7fb9468f9801
```

**Comment by pkujhd** [comment]
#https://github.com/golang/go/issues/47873
#https://go-review.googlesource.com/c/go/+/268479

**Comment by pkujhd** [comment]
waiting newer golang 1.17 version

**Comment by pkujhd** [comment]
golang 1.17.3 fix this bug.  close it
